package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_CAMPAIGN table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_CAMPAIGN"
 */
public abstract class BaseTbCampaign  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_PRODUCT = "Product";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_DISCOUNT_TYPE = "DiscountType";
	public static String PROP_TO_DATE = "ToDate";
	public static String PROP_ID = "Id";
	public static String PROP_FROM_DATE = "FromDate";
	public static String PROP_RATIO = "Ratio";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.util.Date _toDate;
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private java.util.Date _fromDate;
	private java.lang.Integer _ratio;
	private java.lang.Integer _discountType;

	// many to one
	private com.odabasioglu.data.TbProduct _product;


	// constructors
	public BaseTbCampaign () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbCampaign (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbCampaign (
		java.lang.Integer _id,
		com.odabasioglu.data.TbProduct _product,
		java.util.Date _toDate,
		java.util.Date _fromDate,
		java.lang.Integer _ratio,
		java.lang.Integer _discountType) {

		this.setId(_id);
		this.setProduct(_product);
		this.setToDate(_toDate);
		this.setFromDate(_fromDate);
		this.setRatio(_ratio);
		this.setDiscountType(_discountType);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="CAMPAIGN_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: TO_DATE
	 */
	public java.util.Date getToDate () {
		return _toDate;
	}

	/**
	 * Set the value related to the column: TO_DATE
	 * @param _toDate the TO_DATE value
	 */
	public void setToDate (java.util.Date _toDate) {
		this._toDate = _toDate;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: FROM_DATE
	 */
	public java.util.Date getFromDate () {
		return _fromDate;
	}

	/**
	 * Set the value related to the column: FROM_DATE
	 * @param _fromDate the FROM_DATE value
	 */
	public void setFromDate (java.util.Date _fromDate) {
		this._fromDate = _fromDate;
	}


	/**
	 * Return the value associated with the column: RATIO
	 */
	public java.lang.Integer getRatio () {
		return _ratio;
	}

	/**
	 * Set the value related to the column: RATIO
	 * @param _ratio the RATIO value
	 */
	public void setRatio (java.lang.Integer _ratio) {
		this._ratio = _ratio;
	}


	/**
	 * Return the value associated with the column: DISCOUNT_TYPE
	 */
	public java.lang.Integer getDiscountType () {
		return _discountType;
	}

	/**
	 * Set the value related to the column: DISCOUNT_TYPE
	 * @param _discountType the DISCOUNT_TYPE value
	 */
	public void setDiscountType (java.lang.Integer _discountType) {
		this._discountType = _discountType;
	}


	/**
     * @hibernate.property
     *  column=PRODUCT_ID
	 * not-null=true
	 */
	public com.odabasioglu.data.TbProduct getProduct () {
		return this._product;
	}

	/**
	 * Set the value related to the column: PRODUCT_ID
	 * @param _product the PRODUCT_ID value
	 */
	public void setProduct (com.odabasioglu.data.TbProduct _product) {
		this._product = _product;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbCampaign)) return false;
		else {
			com.odabasioglu.data.base.BaseTbCampaign mObj = (com.odabasioglu.data.base.BaseTbCampaign) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}