package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_POINT table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_POINT"
 */
public abstract class BaseTbPoint  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_POINT = "Point";
	public static String PROP_USERS = "Users";
	public static String PROP_POINT_STATUS = "PointStatus";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_POINT_TYPE = "PointType";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private java.util.Date _modifiedDate;
	private java.lang.Integer _pointType;
	private java.lang.Integer _point;
	private java.lang.Integer _pointStatus;

	// many to one
	private com.odabasioglu.data.TbUsers _users;


	// constructors
	public BaseTbPoint () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbPoint (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbPoint (
		java.lang.Integer _id,
		com.odabasioglu.data.TbUsers _users,
		java.lang.Integer _pointType,
		java.lang.Integer _point) {

		this.setId(_id);
		this.setUsers(_users);
		this.setPointType(_pointType);
		this.setPoint(_point);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="POINT_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: MODIFIED_DATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIED_DATE
	 * @param _modifiedDate the MODIFIED_DATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: POINT_TYPE
	 */
	public java.lang.Integer getPointType () {
		return _pointType;
	}

	/**
	 * Set the value related to the column: POINT_TYPE
	 * @param _pointType the POINT_TYPE value
	 */
	public void setPointType (java.lang.Integer _pointType) {
		this._pointType = _pointType;
	}


	/**
	 * Return the value associated with the column: POINT
	 */
	public java.lang.Integer getPoint () {
		return _point;
	}

	/**
	 * Set the value related to the column: POINT
	 * @param _point the POINT value
	 */
	public void setPoint (java.lang.Integer _point) {
		this._point = _point;
	}


	/**
	 * Return the value associated with the column: POINT_STATUS
	 */
	public java.lang.Integer getPointStatus () {
		return _pointStatus;
	}

	/**
	 * Set the value related to the column: POINT_STATUS
	 * @param _pointStatus the POINT_STATUS value
	 */
	public void setPointStatus (java.lang.Integer _pointStatus) {
		this._pointStatus = _pointStatus;
	}


	/**
     * @hibernate.property
     *  column=USERS_ID
	 * not-null=true
	 */
	public com.odabasioglu.data.TbUsers getUsers () {
		return this._users;
	}

	/**
	 * Set the value related to the column: USERS_ID
	 * @param _users the USERS_ID value
	 */
	public void setUsers (com.odabasioglu.data.TbUsers _users) {
		this._users = _users;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbPoint)) return false;
		else {
			com.odabasioglu.data.base.BaseTbPoint mObj = (com.odabasioglu.data.base.BaseTbPoint) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}