package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_CURRENCY table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_CURRENCY"
 */
public abstract class BaseTbCurrency  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_USD = "Usd";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_EURO = "Euro";
	public static String PROP_CURRENCY_DATE = "CurrencyDate";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private float _euro;
	private float _usd;
	private java.util.Date _currencyDate;


	// constructors
	public BaseTbCurrency () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbCurrency (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbCurrency (
		java.lang.Integer _id,
		float _euro,
		float _usd,
		java.util.Date _currencyDate) {

		this.setId(_id);
		this.setEuro(_euro);
		this.setUsd(_usd);
		this.setCurrencyDate(_currencyDate);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="CURRENCY_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: EURO
	 */
	public float getEuro () {
		return _euro;
	}

	/**
	 * Set the value related to the column: EURO
	 * @param _euro the EURO value
	 */
	public void setEuro (float _euro) {
		this._euro = _euro;
	}


	/**
	 * Return the value associated with the column: USD
	 */
	public float getUsd () {
		return _usd;
	}

	/**
	 * Set the value related to the column: USD
	 * @param _usd the USD value
	 */
	public void setUsd (float _usd) {
		this._usd = _usd;
	}


	/**
	 * Return the value associated with the column: CURRENCY_DATE
	 */
	public java.util.Date getCurrencyDate () {
		return _currencyDate;
	}

	/**
	 * Set the value related to the column: CURRENCY_DATE
	 * @param _currencyDate the CURRENCY_DATE value
	 */
	public void setCurrencyDate (java.util.Date _currencyDate) {
		this._currencyDate = _currencyDate;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbCurrency)) return false;
		else {
			com.odabasioglu.data.base.BaseTbCurrency mObj = (com.odabasioglu.data.base.BaseTbCurrency) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}