package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_TOPSALES table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_TOPSALES"
 */
public abstract class BaseTbTopsales  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_PRODUCT = "Product";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_PERCENTAGE = "Percentage";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private java.lang.Integer _percentage;

	// many to one
	private com.odabasioglu.data.TbProduct _product;


	// constructors
	public BaseTbTopsales () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbTopsales (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbTopsales (
		java.lang.Integer _id,
		com.odabasioglu.data.TbProduct _product,
		java.lang.Integer _percentage) {

		this.setId(_id);
		this.setProduct(_product);
		this.setPercentage(_percentage);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="TOPSALES_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: PERCENTAGE
	 */
	public java.lang.Integer getPercentage () {
		return _percentage;
	}

	/**
	 * Set the value related to the column: PERCENTAGE
	 * @param _percentage the PERCENTAGE value
	 */
	public void setPercentage (java.lang.Integer _percentage) {
		this._percentage = _percentage;
	}


	/**
     * @hibernate.property
     *  column=PRODUCT_ID
	 * not-null=true
	 */
	public com.odabasioglu.data.TbProduct getProduct () {
		return this._product;
	}

	/**
	 * Set the value related to the column: PRODUCT_ID
	 * @param _product the PRODUCT_ID value
	 */
	public void setProduct (com.odabasioglu.data.TbProduct _product) {
		this._product = _product;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbTopsales)) return false;
		else {
			com.odabasioglu.data.base.BaseTbTopsales mObj = (com.odabasioglu.data.base.BaseTbTopsales) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}