package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_LOGS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_LOGS"
 */
public abstract class BaseTbLogs  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_USER_ID = "UserId";
	public static String PROP_LOG_TYPE = "LogType";
	public static String PROP_OBJECT_NAME = "ObjectName";
	public static String PROP_OBJECT_DESC = "ObjectDesc";
	public static String PROP_OPERATION_TYPE = "OperationType";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_LOG_IP = "LogIp";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _objectName;
	private java.lang.String _objectDesc;
	private java.lang.Integer _status;
	private java.util.Date _modifiedDate;
	private java.lang.Integer _logType;
	private java.lang.Integer _userId;
	private java.lang.String _logIp;
	private java.lang.String _operationType;


	// constructors
	public BaseTbLogs () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbLogs (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbLogs (
		java.lang.Integer _id,
		java.lang.String _objectName,
		java.lang.String _objectDesc,
		java.util.Date _modifiedDate,
		java.lang.Integer _userId,
		java.lang.String _logIp,
		java.lang.String _operationType) {

		this.setId(_id);
		this.setObjectName(_objectName);
		this.setModifiedDate(_modifiedDate);
		this.setUserId(_userId);
		this.setLogIp(_logIp);
		this.setOperationType(_operationType);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="LOG_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: OBJECT_NAME
	 */
	public java.lang.String getObjectName () {
		return _objectName;
	}

	/**
	 * Set the value related to the column: OBJECT_NAME
	 * @param _objectName the OBJECT_NAME value
	 */
	public void setObjectName (java.lang.String _objectName) {
		this._objectName = _objectName;
	}

	/**
	 * Return the value associated with the column: OBJECT_NAME
	 */
	public java.lang.String getObjectDesc () {
		return _objectDesc;
	}

	/**
	 * Set the value related to the column: OBJECT_NAME
	 * @param _objectName the OBJECT_NAME value
	 */
	public void setObjectDesc (java.lang.String _objectDesc) {
		this._objectDesc = _objectDesc;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: MODIFIED_DATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIED_DATE
	 * @param _modifiedDate the MODIFIED_DATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: LOG_TYPE
	 */
	public java.lang.Integer getLogType () {
		return _logType;
	}

	/**
	 * Set the value related to the column: LOG_TYPE
	 * @param _logType the LOG_TYPE value
	 */
	public void setLogType (java.lang.Integer _logType) {
		this._logType = _logType;
	}


	/**
	 * Return the value associated with the column: USER_ID
	 */
	public java.lang.String getLogIp () {
		return _logIp;
	}

	/**
	 * Set the value related to the column: USER_ID
	 * @param _userId the USER_ID value
	 */
	public void setLogIp (java.lang.String _logIp) {
		this._logIp = _logIp;
	}

	/**
	 * Return the value associated with the column: USER_ID
	 */
	public java.lang.Integer getUserId () {
		return _userId;
	}

	/**
	 * Set the value related to the column: USER_ID
	 * @param _userId the USER_ID value
	 */
	public void setUserId (java.lang.Integer _userId) {
		this._userId = _userId;
	}


	/**
	 * Return the value associated with the column: OPERATION_TYPE
	 */
	public java.lang.String getOperationType () {
		return _operationType;
	}

	/**
	 * Set the value related to the column: OPERATION_TYPE
	 * @param _operationType the OPERATION_TYPE value
	 */
	public void setOperationType (java.lang.String _operationType) {
		this._operationType = _operationType;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbLogs)) return false;
		else {
			com.odabasioglu.data.base.BaseTbLogs mObj = (com.odabasioglu.data.base.BaseTbLogs) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}