package com.odabasioglu.data.dao;

import com.odabasioglu.data.base.BaseTbLastvisitDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the TB_LASTVISIT table.
 * Any customizations belong here.
 */
public class TbLastvisitDAO extends BaseTbLastvisitDAO {

}