package com.odabasioglu.data.dao;

import org.hibernate.HibernateException;

import com.odabasioglu.data.TbOrder;
import com.odabasioglu.data.base.BaseTbOrderlineDAO;
import com.odabasioglu.utility.HibernateUtility;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the TB_ORDERLINE table.
 * Any customizations belong here.
 */ 
public class TbOrderlineDAO extends BaseTbOrderlineDAO{

	
}
