package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_ORDERLINE table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_ORDERLINE"
 */
public abstract class BaseTbOrderline  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_AMOUNT = "Amount";
	public static String PROP_PRICE = "Price";
	public static String PROP_PRODUCT = "Product";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_USERS = "Users";
	public static String PROP_ID = "Id";
	public static String PROP_ORDER_ID = "OrderId";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _amount;
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private float _price;
	private java.lang.Integer _orderId;

	// many to one
	private com.odabasioglu.data.TbProduct _product;
	private com.odabasioglu.data.TbUsers _users;


	// constructors
	public BaseTbOrderline () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbOrderline (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbOrderline (
		java.lang.Integer _id,
		com.odabasioglu.data.TbProduct _product,
		com.odabasioglu.data.TbUsers _users,
		java.lang.Integer _amount,
		float _price) {

		this.setId(_id);
		this.setProduct(_product);
		this.setUsers(_users);
		this.setAmount(_amount);
		this.setPrice(_price);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="ORDERLINE_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AMOUNT
	 */
	public java.lang.Integer getAmount () {
		return _amount;
	}

	/**
	 * Set the value related to the column: AMOUNT
	 * @param _amount the AMOUNT value
	 */
	public void setAmount (java.lang.Integer _amount) {
		this._amount = _amount;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: PRICE
	 */
	public float getPrice () {
		return _price;
	}

	/**
	 * Set the value related to the column: PRICE
	 * @param _price the PRICE value
	 */
	public void setPrice (float _price) {
		this._price = _price;
	}


	/**
	 * Return the value associated with the column: ORDER_ID
	 */
	public java.lang.Integer getOrderId () {
		return _orderId;
	}

	/**
	 * Set the value related to the column: ORDER_ID
	 * @param _orderId the ORDER_ID value
	 */
	public void setOrderId (java.lang.Integer _orderId) {
		this._orderId = _orderId;
	}


	/**
     * @hibernate.property
     *  column=PRODUCT_ID
	 * not-null=true
	 */
	public com.odabasioglu.data.TbProduct getProduct () {
		return this._product;
	}

	/**
	 * Set the value related to the column: PRODUCT_ID
	 * @param _product the PRODUCT_ID value
	 */
	public void setProduct (com.odabasioglu.data.TbProduct _product) {
		this._product = _product;
	}


	/**
     * @hibernate.property
     *  column=USERS_ID
	 * not-null=true
	 */
	public com.odabasioglu.data.TbUsers getUsers () {
		return this._users;
	}

	/**
	 * Set the value related to the column: USERS_ID
	 * @param _users the USERS_ID value
	 */
	public void setUsers (com.odabasioglu.data.TbUsers _users) {
		this._users = _users;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbOrderline)) return false;
		else {
			com.odabasioglu.data.base.BaseTbOrderline mObj = (com.odabasioglu.data.base.BaseTbOrderline) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}