package com.odabasioglu.data.base;

import java.io.File;
import java.io.Serializable;

import com.odabasioglu.config.SystemConstants;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_CATEGORY table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_CATEGORY"
 */
public abstract class BaseTbCategory  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_IS_MAIN = "IsMain";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_MAIN_CATEGORY_ID = "MainCategoryId";
	public static String PROP_CATEGORY_NAME = "CategoryName";
	public static String PROP_CATEGORY_TYPE = "CategoryType";
	public static String PROP_CATEGORY_DESCRIPTION = "CategoryDescription";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private java.util.Date _modifiedDate;
	private java.lang.Integer _isMain;
	private java.lang.Integer _mainCategoryId;
	private java.lang.String _categoryDescription;
	private java.lang.String _categoryName;
	private java.lang.Integer _categoryType;
	private byte[] _thumbnail;

	// collections
	private java.util.Set _tbProductSet;


	// constructors
	public BaseTbCategory () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbCategory (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbCategory (
		java.lang.Integer _id,
		java.util.Date _modifiedDate,
		java.lang.Integer _isMain,
		java.lang.Integer _mainCategoryId,
		java.lang.String _categoryDescription,
		java.lang.String _categoryName,
		java.lang.String _picture) {

		this.setId(_id);
		this.setModifiedDate(_modifiedDate);
		this.setIsMain(_isMain);
		this.setMainCategoryId(_mainCategoryId);
		this.setCategoryDescription(_categoryDescription);
		this.setCategoryName(_categoryName);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="CATEGORY_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: MODIFIED_DATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIED_DATE
	 * @param _modifiedDate the MODIFIED_DATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: IS_MAIN
	 */
	public java.lang.Integer getIsMain () {
		return _isMain;
	}

	/**
	 * Set the value related to the column: IS_MAIN
	 * @param _isMain the IS_MAIN value
	 */
	public void setIsMain (java.lang.Integer _isMain) {
		this._isMain = _isMain;
	}


	/**
	 * Return the value associated with the column: MAIN_CATEGORY_ID
	 */
	public java.lang.Integer getMainCategoryId () {
		return _mainCategoryId;
	}

	/**
	 * Set the value related to the column: MAIN_CATEGORY_ID
	 * @param _mainCategoryId the MAIN_CATEGORY_ID value
	 */
	public void setMainCategoryId (java.lang.Integer _mainCategoryId) {
		this._mainCategoryId = _mainCategoryId;
	}


	/**
	 * Return the value associated with the column: CATEGORY_DESCRIPTION
	 */
	public java.lang.String getCategoryDescription () {
		return _categoryDescription;
	}

	/**
	 * Set the value related to the column: CATEGORY_DESCRIPTION
	 * @param _categoryDescription the CATEGORY_DESCRIPTION value
	 */
	public void setCategoryDescription (java.lang.String _categoryDescription) {
		this._categoryDescription = _categoryDescription;
	}


	/**
	 * Return the value associated with the column: CATEGORY_NAME
	 */
	public java.lang.String getCategoryName () {
		return _categoryName;
	}

	/**
	 * Set the value related to the column: CATEGORY_NAME
	 * @param _categoryName the CATEGORY_NAME value
	 */
	public void setCategoryName (java.lang.String _categoryName) {
		this._categoryName = _categoryName;
	}

	public void setThumbnail (byte[] _thumbnail) {
		this._thumbnail = _thumbnail;
	}

	public byte[] getThumbnail () {
		return _thumbnail;
	}
	/**
	 * Return the value associated with the column: CATEGORY_TYPE
	 */
	public java.lang.Integer getCategoryType () {
		return _categoryType;
	}

	/**
	 * Set the value related to the column: CATEGORY_TYPE
	 * @param _categoryType the CATEGORY_TYPE value
	 */
	public void setCategoryType (java.lang.Integer _categoryType) {
		this._categoryType = _categoryType;
	}


		/**
	 * Return the value associated with the column: TbProductSet
	 */
	public java.util.Set getTbProductSet () {
		return this._tbProductSet;
	}

	/**
	 * Set the value related to the column: TbProductSet
	 * @param _tbProductSet the TbProductSet value
	 */
	public void setTbProductSet (java.util.Set _tbProductSet) {
		this._tbProductSet = _tbProductSet;
	}
	
	public void addToTbProductSet (Object obj) {
		if (null == this._tbProductSet) this._tbProductSet = new java.util.HashSet();
		this._tbProductSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbCategory)) return false;
		else {
			com.odabasioglu.data.base.BaseTbCategory mObj = (com.odabasioglu.data.base.BaseTbCategory) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}