package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_FORM table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_FORM"
 */
public abstract class BaseTbForm  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_TOPIC = "Topic";
	public static String PROP_FORM_STATUS = "FormStatus";
	public static String PROP_USERS = "Users";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private java.util.Date _modifiedDate;
	private java.lang.String _description;
	private java.lang.Integer _formStatus;
	private java.lang.String _topic;

	// many to one
	private com.odabasioglu.data.TbUsers _users;


	// constructors
	public BaseTbForm () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbForm (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbForm (
		java.lang.Integer _id,
		com.odabasioglu.data.TbUsers _users,
		java.util.Date _modifiedDate,
		java.lang.String _description,
		java.lang.Integer _formStatus,
		java.lang.String _topic) {

		this.setId(_id);
		this.setUsers(_users);
		this.setModifiedDate(_modifiedDate);
		this.setDescription(_description);
		this.setFormStatus(_formStatus);
		this.setTopic(_topic);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="FORM_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: MODIFIED_DATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIED_DATE
	 * @param _modifiedDate the MODIFIED_DATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: FORM_STATUS
	 */
	public java.lang.Integer getFormStatus () {
		return _formStatus;
	}

	/**
	 * Set the value related to the column: FORM_STATUS
	 * @param _formStatus the FORM_STATUS value
	 */
	public void setFormStatus (java.lang.Integer _formStatus) {
		this._formStatus = _formStatus;
	}


	/**
	 * Return the value associated with the column: TOPIC
	 */
	public java.lang.String getTopic () {
		return _topic;
	}

	/**
	 * Set the value related to the column: TOPIC
	 * @param _topic the TOPIC value
	 */
	public void setTopic (java.lang.String _topic) {
		this._topic = _topic;
	}


	/**
     * @hibernate.property
     *  column=USERS_ID
	 * not-null=true
	 */
	public com.odabasioglu.data.TbUsers getUsers () {
		return this._users;
	}

	/**
	 * Set the value related to the column: USERS_ID
	 * @param _users the USERS_ID value
	 */
	public void setUsers (com.odabasioglu.data.TbUsers _users) {
		this._users = _users;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbForm)) return false;
		else {
			com.odabasioglu.data.base.BaseTbForm mObj = (com.odabasioglu.data.base.BaseTbForm) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}