package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_ADDRESS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_ADDRESS"
 */
public abstract class BaseTbAddress  implements Serializable {

	public static String PROP_POSTAL_CODE = "PostalCode";
	public static String PROP_STATUS = "Status";
	public static String PROP_STATE = "State";
	public static String PROP_LINE2 = "Line2";
	public static String PROP_ADDRESS_TYPE = "AddressType";
	public static String PROP_CITY = "City";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_TAX_OFFICE = "TaxOffice";
	public static String PROP_SHORT_NAME = "ShortName";
	public static String PROP_TAX_NO = "TaxNo";
	public static String PROP_COUNTRY = "Country";
	public static String PROP_USERS = "Users";
	public static String PROP_LINE1 = "Line1";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _state;
	private java.lang.String _taxNo;
	private java.lang.String _line1;
	private java.lang.String _country;
	private java.lang.String _postalCode;
	private java.lang.String _line2;
	private java.lang.String _shortName;
	private java.lang.Integer _logId;
	private java.lang.String _taxOffice;
	private java.lang.Integer _status;
	private java.lang.String _city;
	private java.lang.Integer _addressType;

	// many to one
	private com.odabasioglu.data.TbUsers _users;


	// constructors
	public BaseTbAddress () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbAddress (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbAddress (
		java.lang.Integer _id,
		com.odabasioglu.data.TbUsers _users,
		java.lang.String _state,
		java.lang.String _line1,
		java.lang.String _country,
		java.lang.String _postalCode,
		java.lang.String _line2,
		java.lang.String _shortName,
		java.lang.String _city) {

		this.setId(_id);
		this.setUsers(_users);
		this.setState(_state);
		this.setLine1(_line1);
		this.setCountry(_country);
		this.setPostalCode(_postalCode);
		this.setLine2(_line2);
		this.setShortName(_shortName);
		this.setCity(_city);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="ADDRESS_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: STATE
	 */
	public java.lang.String getState () {
		return _state;
	}

	/**
	 * Set the value related to the column: STATE
	 * @param _state the STATE value
	 */
	public void setState (java.lang.String _state) {
		this._state = _state;
	}


	/**
	 * Return the value associated with the column: TAX_NO
	 */
	public java.lang.String getTaxNo () {
		return _taxNo;
	}

	/**
	 * Set the value related to the column: TAX_NO
	 * @param _taxNo the TAX_NO value
	 */
	public void setTaxNo (java.lang.String _taxNo) {
		this._taxNo = _taxNo;
	}


	/**
	 * Return the value associated with the column: LINE1
	 */
	public java.lang.String getLine1 () {
		return _line1;
	}

	/**
	 * Set the value related to the column: LINE1
	 * @param _line1 the LINE1 value
	 */
	public void setLine1 (java.lang.String _line1) {
		this._line1 = _line1;
	}


	/**
	 * Return the value associated with the column: COUNTRY
	 */
	public java.lang.String getCountry () {
		return _country;
	}

	/**
	 * Set the value related to the column: COUNTRY
	 * @param _country the COUNTRY value
	 */
	public void setCountry (java.lang.String _country) {
		this._country = _country;
	}


	/**
	 * Return the value associated with the column: POSTAL_CODE
	 */
	public java.lang.String getPostalCode () {
		return _postalCode;
	}

	/**
	 * Set the value related to the column: POSTAL_CODE
	 * @param _postalCode the POSTAL_CODE value
	 */
	public void setPostalCode (java.lang.String _postalCode) {
		this._postalCode = _postalCode;
	}


	/**
	 * Return the value associated with the column: LINE2
	 */
	public java.lang.String getLine2 () {
		return _line2;
	}

	/**
	 * Set the value related to the column: LINE2
	 * @param _line2 the LINE2 value
	 */
	public void setLine2 (java.lang.String _line2) {
		this._line2 = _line2;
	}


	/**
	 * Return the value associated with the column: SHORT_NAME
	 */
	public java.lang.String getShortName () {
		return _shortName;
	}

	/**
	 * Set the value related to the column: SHORT_NAME
	 * @param _shortName the SHORT_NAME value
	 */
	public void setShortName (java.lang.String _shortName) {
		this._shortName = _shortName;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: TAX_OFFICE
	 */
	public java.lang.String getTaxOffice () {
		return _taxOffice;
	}

	/**
	 * Set the value related to the column: TAX_OFFICE
	 * @param _taxOffice the TAX_OFFICE value
	 */
	public void setTaxOffice (java.lang.String _taxOffice) {
		this._taxOffice = _taxOffice;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: CITY
	 */
	public java.lang.String getCity () {
		return _city;
	}

	/**
	 * Set the value related to the column: CITY
	 * @param _city the CITY value
	 */
	public void setCity (java.lang.String _city) {
		this._city = _city;
	}


	/**
	 * Return the value associated with the column: ADDRESS_TYPE
	 */
	public java.lang.Integer getAddressType () {
		return _addressType;
	}

	/**
	 * Set the value related to the column: ADDRESS_TYPE
	 * @param _addressType the ADDRESS_TYPE value
	 */
	public void setAddressType (java.lang.Integer _addressType) {
		this._addressType = _addressType;
	}


	/**
     * @hibernate.property
     *  column=USERS_ID
	 * not-null=true
	 */
	public com.odabasioglu.data.TbUsers getUsers () {
		return this._users;
	}

	/**
	 * Set the value related to the column: USERS_ID
	 * @param _users the USERS_ID value
	 */
	public void setUsers (com.odabasioglu.data.TbUsers _users) {
		this._users = _users;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbAddress)) return false;
		else {
			com.odabasioglu.data.base.BaseTbAddress mObj = (com.odabasioglu.data.base.BaseTbAddress) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}