package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_NEWS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_NEWS"
 */
public abstract class BaseTbNews  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_NEWSDESCRIPTION = "Newsdescription";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_TITLE = "Title";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _logId;
	private java.lang.String _title;
	private java.lang.Integer _status;
	private java.lang.String _newsdescription;


	// constructors
	public BaseTbNews () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbNews (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbNews (
		java.lang.Integer _id,
		java.lang.String _title,
		java.lang.String _newsdescription) {

		this.setId(_id);
		this.setTitle(_title);
		this.setNewsdescription(_newsdescription);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="NEWS_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: TITLE
	 */
	public java.lang.String getTitle () {
		return _title;
	}

	/**
	 * Set the value related to the column: TITLE
	 * @param _title the TITLE value
	 */
	public void setTitle (java.lang.String _title) {
		this._title = _title;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: NEWSDESCRIPTION
	 */
	public java.lang.String getNewsdescription () {
		return _newsdescription;
	}

	/**
	 * Set the value related to the column: NEWSDESCRIPTION
	 * @param _newsdescription the NEWSDESCRIPTION value
	 */
	public void setNewsdescription (java.lang.String _newsdescription) {
		this._newsdescription = _newsdescription;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbNews)) return false;
		else {
			com.odabasioglu.data.base.BaseTbNews mObj = (com.odabasioglu.data.base.BaseTbNews) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}