package com.odabasioglu.data.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TB_STOCK table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TB_STOCK"
 */
public abstract class BaseTbStock  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_AMOUNT = "Amount";
	public static String PROP_LOG_ID = "LogId";
	public static String PROP_STOCK_STATUS = "StockStatus";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_INFO = "Info";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _amount;
	private java.lang.Integer _logId;
	private java.lang.Integer _status;
	private java.util.Date _modifiedDate;
	private java.lang.String _info;
	private java.lang.Integer _stockStatus;


	// constructors
	public BaseTbStock () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTbStock (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTbStock (
		java.lang.Integer _id,
		java.lang.Integer _amount,
		java.util.Date _modifiedDate,
		java.lang.String _info,
		java.lang.Integer _stockStatus) {

		this.setId(_id);
		this.setAmount(_amount);
		this.setModifiedDate(_modifiedDate);
		this.setInfo(_info);
		this.setStockStatus(_stockStatus);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="STOCK_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AMOUNT
	 */
	public java.lang.Integer getAmount () {
		return _amount;
	}

	/**
	 * Set the value related to the column: AMOUNT
	 * @param _amount the AMOUNT value
	 */
	public void setAmount (java.lang.Integer _amount) {
		this._amount = _amount;
	}


	/**
	 * Return the value associated with the column: LOG_ID
	 */
	public java.lang.Integer getLogId () {
		return _logId;
	}

	/**
	 * Set the value related to the column: LOG_ID
	 * @param _logId the LOG_ID value
	 */
	public void setLogId (java.lang.Integer _logId) {
		this._logId = _logId;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: MODIFIED_DATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIED_DATE
	 * @param _modifiedDate the MODIFIED_DATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: INFO
	 */
	public java.lang.String getInfo () {
		return _info;
	}

	/**
	 * Set the value related to the column: INFO
	 * @param _info the INFO value
	 */
	public void setInfo (java.lang.String _info) {
		this._info = _info;
	}


	/**
	 * Return the value associated with the column: STOCK_STATUS
	 */
	public java.lang.Integer getStockStatus () {
		return _stockStatus;
	}

	/**
	 * Set the value related to the column: STOCK_STATUS
	 * @param _stockStatus the STOCK_STATUS value
	 */
	public void setStockStatus (java.lang.Integer _stockStatus) {
		this._stockStatus = _stockStatus;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.odabasioglu.data.base.BaseTbStock)) return false;
		else {
			com.odabasioglu.data.base.BaseTbStock mObj = (com.odabasioglu.data.base.BaseTbStock) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}